#!/usr/bin/env zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

missing=0

require_in_file() {
  local file="$1"
  local pattern="$2"
  local label="$3"

  if ! grep -qE -- "$pattern" "$file"; then
    echo "Missing value surface: $label in $file" >&2
    missing=1
  fi
}

require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Start Here' "Start Here app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Terminal Brain Now' "Now app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Value Now' "Value Now app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'selectedSection = "use-now"' "Use Now default app section"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Text\("Learn"\)' "sidebar Learn group"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Text\("Signals"\)' "sidebar Signals group"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'workBlockView' "Work Block app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Top Review Action' "Work Block direct review actions"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'delegateOracleCommitToStartWork\(topReview\)' "Work Block delegate action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'focusIdeaCapturePanel\(focus\)' "Work Block capture thought panel"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'firstMinuteView' "First Minute app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'demoView' "Demo app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'playbookView' "Playbook app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'valueAuditView' "Value Audit app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'focusIdeaCapturePanel\(focus\)' "First Minute capture thought panel"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open First Minute' "command palette can open First Minute"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Use Now' "command palette can open Use Now"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Demo' "command palette can open Demo"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Playbook' "command palette can open Playbook"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Value Audit' "command palette can open Value Audit"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Ideas' "command palette can open Ideas"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'focusIdeaCapturePanel\(focus\)' "Ideas includes direct capture lane"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Memory' "command palette can open Memory"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Work Block' "command palette can open Work Block"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Now' "command palette can open Now"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Check Blindspots' "Radar routes to counter-signal review"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Capture as Idea' "Blindspots can become tracked ideas"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Start Here' "Start Here menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Now' "Now menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Demo' "Demo menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Playbook' "Playbook menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Value Audit' "Value Audit menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Source Inventory' "Source Inventory menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Memory Brief' "Memory Brief menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Oracle Brief' "Oracle Brief menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Process Map' "Process Map menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Cleanup Plan' "Cleanup Plan menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Support Bundle' "Support Bundle menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Work Block' "Work Block menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Commit Outcome' "in-app outcome close loop"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Oracle Digest' "Oracle Digest app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'memoryBriefView' "Memory Brief app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Copy Memory Brief' "Memory Brief in-app copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Preview' "Memory Brief preview action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Promote' "Memory Brief promote action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func commitOutcome' "in-app structured outcome writer"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyFirstMinute' "in-app First Minute copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyDemo' "in-app Demo copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyPlaybook' "in-app Playbook copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyValueAudit' "in-app Value Audit copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyNow' "in-app Now copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyUseNow' "in-app Use Now copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyOracleBrief' "in-app Oracle Brief copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyProcessMap' "in-app Process Map copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyCleanupPlan' "in-app Cleanup Plan copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copySupportBundle' "in-app Support Bundle copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyWorkBlock' "in-app Work Block copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copySourceInventory' "in-app Source Inventory copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyMemoryBrief' "in-app Memory Brief copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func promoteMemoryLead' "in-app Memory Promote action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func promoteRecentWork' "in-app Recent Work Promote action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyNowIntent' "Copy Now App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyUseNowIntent' "Copy Use Now App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyFirstMinuteIntent' "Copy First Minute App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyDemoIntent' "Copy Demo App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyPlaybookIntent' "Copy Playbook App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyValueAuditIntent' "Copy Value Audit App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyOracleBriefIntent' "Copy Oracle Brief App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyProcessMapIntent' "Copy Process Map App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyCleanupPlanIntent' "Copy Cleanup Plan App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopySupportBundleIntent' "Copy Support Bundle App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyWorkBlockIntent' "Copy Work Block App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopySourceInventoryIntent' "Copy Source Inventory App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyMemoryBriefIntent' "Copy Memory Brief App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyValueProofIntent' "Copy Value Proof App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CommitBrainOutcomeIntent' "Commit Outcome App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyStartHereIntent' "Copy Start Here App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyOracleDigestIntent' "Copy Oracle Digest App Shortcut"

require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/start-here/markdown"' "Start Here API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/use-now/markdown"' "Use Now API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/sources/markdown"' "Source Inventory API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/memory/markdown"' "Memory Brief API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/memory/promote"' "Memory Promote API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/recent-work/promote"' "Recent Work Promote API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/first-minute/markdown"' "First Minute API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/demo/markdown"' "Demo API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/playbook/markdown"' "Playbook API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/value-audit/markdown"' "Value Audit API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/now/markdown"' "Now API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/now"' "Now JSON API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/cleanup-plan/markdown"' "Cleanup Plan API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/process-map/markdown"' "Process Map API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/support-bundle/markdown"' "Support Bundle API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/work-block/markdown"' "Work Block API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/value-proof/markdown"' "Value Proof API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/oracle/brief/markdown"' "Oracle Brief API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/oracle-digest/markdown"' "Oracle Digest API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/outcomes/commit"' "Outcome commit API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'reviewStatus: "accepted"' "outcomes close as accepted"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/ideas/capture"' "Idea Capture API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '## Cheap Test' "Idea Capture API prompts for cheap test"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '## Kill Criteria' "Idea Capture API prompts for kill criteria"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum StartHereSnapshot' "Start Here Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum FirstMinuteSnapshot' "First Minute Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum ScriptMarkdownSnapshot' "Script-backed value Markdown artifacts"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum NowSnapshot' "Now Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum CleanupPlanSnapshot' "Cleanup Plan Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum ProcessMapSnapshot' "Process Map Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum SupportBundleSnapshot' "Support Bundle Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum WorkBlockSnapshot' "Work Block Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum ValueProofSnapshot' "Value Proof Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'static func markdown\(\) async -> String' "Oracle Brief Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum OracleDigestSnapshot' "Oracle Digest artifact"

require_in_file "$ROOT/mac-app/scripts/snapshot.zsh" '--start-here' "Start Here CLI flag"
require_in_file "$ROOT/mac-app/scripts/snapshot.zsh" '--digest' "Oracle Digest CLI flag"
require_in_file "$ROOT/mac-app/scripts/idea.zsh" 'local-fallback' "Idea CLI local fallback"
require_in_file "$ROOT/mac-app/scripts/idea.zsh" 'reviewStatus: new' "Idea fallback opens review"
require_in_file "$ROOT/mac-app/scripts/idea.zsh" '## Cheap Test' "Idea fallback prompts for cheap test"
require_in_file "$ROOT/mac-app/scripts/idea.zsh" '## Kill Criteria' "Idea fallback prompts for kill criteria"
require_in_file "$ROOT/mac-app/scripts/review.zsh" 'Terminal Brain Review Queue' "Review Queue CLI"
require_in_file "$ROOT/mac-app/scripts/review.zsh" 'make review-status' "Review Queue action commands"
require_in_file "$ROOT/mac-app/scripts/review.zsh" 'did not launch, foreground, quit, kill, or control Terminal Brain' "Review Queue guardrail"
require_in_file "$ROOT/mac-app/scripts/review-status.zsh" 'reviewStatus' "Review Status CLI"
require_in_file "$ROOT/mac-app/scripts/review-status.zsh" 'did not launch or foreground Terminal Brain' "Review Status guardrail"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'Terminal Brain Bubble Up' "Bubble Up CLI"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'What You May Not Be Considering' "Bubble Up under-considered signals"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'Prime The Brain' "Bubble Up actionable empty state"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'Recent Work Signals' "Bubble Up recent work fallback"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'Completed Evidence' "Bubble Up completed evidence lane"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'make recent-work' "Bubble Up recent work promotion command"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'Decision pressure' "Bubble Up starter capture"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'make review-status' "Bubble Up action commands"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'did not launch, foreground, quit, kill, or control Terminal Brain' "Bubble Up guardrail"
require_in_file "$ROOT/mac-app/scripts/recent-work.zsh" 'Terminal Brain Recent Work' "Recent Work promotion source"
require_in_file "$ROOT/mac-app/scripts/recent-work.zsh" 'recent-work promotion did not launch or foreground' "Recent Work guardrail"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'Terminal Brain Work Block' "Work Block CLI"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'bubble-up.zsh' "Work Block includes Bubble Up"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'Prime The Brain' "Work Block actionable empty state"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'Next Clean Move' "Work Block no-open-item guidance"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'Broader Queue' "Work Block points to broader queue"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'make review' "Work Block review queue command"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'make outcome' "Work Block close-loop command"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'did not launch, foreground, quit, kill, or control Terminal Brain' "Work Block guardrail"
require_in_file "$ROOT/mac-app/scripts/outcome.zsh" '/outcomes/commit' "Outcome CLI API writeback"
require_in_file "$ROOT/mac-app/scripts/outcome.zsh" 'local-fallback' "Outcome CLI local fallback"
require_in_file "$ROOT/mac-app/scripts/outcome.zsh" 'reviewStatus: accepted' "Outcome fallback closes as accepted"
require_in_file "$ROOT/mac-app/scripts/now.zsh" 'Terminal Brain Now' "non-launching Now orientation"
require_in_file "$ROOT/mac-app/scripts/now.zsh" 'make use-now' "Now starts with Use Now"
require_in_file "$ROOT/mac-app/scripts/now.zsh" 'make outcome' "Now outcome close loop"
require_in_file "$ROOT/mac-app/scripts/sources.zsh" 'Terminal Brain Source Inventory' "non-launching source inventory"
require_in_file "$ROOT/mac-app/scripts/sources.zsh" 'Codex local history' "source inventory Codex coverage"
require_in_file "$ROOT/mac-app/scripts/sources.zsh" 'Claude local history' "source inventory Claude coverage"
require_in_file "$ROOT/mac-app/scripts/sources.zsh" 'does not dump raw transcript content' "source inventory raw transcript guardrail"
require_in_file "$ROOT/mac-app/scripts/memory.zsh" 'Terminal Brain Memory Brief' "non-launching memory brief"
require_in_file "$ROOT/mac-app/scripts/memory.zsh" 'Continuity Leads' "memory brief continuity leads"
require_in_file "$ROOT/mac-app/scripts/memory.zsh" 'Promote If Useful' "memory brief promotion command"
require_in_file "$ROOT/mac-app/scripts/memory.zsh" 'does not dump raw Codex or Claude transcript bodies' "memory brief raw transcript guardrail"
require_in_file "$ROOT/mac-app/scripts/memory-promote.zsh" 'Terminal Brain Memory Brief' "memory promotion source label"
require_in_file "$ROOT/mac-app/scripts/memory-promote.zsh" 'idea.zsh' "memory promotion writes through idea fallback"
require_in_file "$ROOT/mac-app/scripts/memory-promote.zsh" 'derived summaries only' "memory promotion raw transcript guardrail"
require_in_file "$ROOT/mac-app/scripts/status.zsh" 'App process' "non-launching status process check"
require_in_file "$ROOT/mac-app/scripts/processes.zsh" 'Terminal Brain Process Map' "non-launching process map"
require_in_file "$ROOT/mac-app/scripts/processes.zsh" 'did not launch, foreground, quit, kill, or control anything' "process map guardrail"
require_in_file "$ROOT/mac-app/scripts/cleanup-plan.zsh" 'Terminal Brain Cleanup Plan' "non-destructive cleanup plan"
require_in_file "$ROOT/mac-app/scripts/cleanup-plan.zsh" 'did not launch, foreground, quit, kill, or control anything' "cleanup plan guardrail"
require_in_file "$ROOT/mac-app/scripts/cleanup-plan.zsh" 'No Aggregate Kill Command' "cleanup plan suppresses broad kills"
require_in_file "$ROOT/mac-app/scripts/cleanup-plan.zsh" 'codex_count.*-le 1' "cleanup plan only prints kill command in low-risk state"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Terminal Brain Support Bundle' "non-launching support bundle"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Oracle Brief' "support bundle includes Oracle Brief"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Bubble Up' "support bundle includes Bubble Up"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Work Block' "support bundle includes Work Block"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'did not launch, foreground, quit, kill, or control anything' "support bundle guardrail"
require_in_file "$ROOT/mac-app/scripts/handoff.zsh" 'local closed-app handoff' "handoff closed-app fallback"
require_in_file "$ROOT/mac-app/scripts/handoff.zsh" 'snapshot.zsh.*--start-here' "handoff includes Start Here fallback"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'Terminal Brain Use Now' "non-launching Use Now path"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'Captured First Signal' "Use Now optional idea capture"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'idea.zsh' "Use Now writes capture through idea fallback"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'What You Get In 60 Seconds' "Use Now immediate value"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" '## One Move' "Use Now one-move section"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'Why This Move' "Use Now explains the selected move"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'Choose Your Mode' "Use Now explicit operator mode menu"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'make ask-commit QUERY=.*clean' "Use Now clean-queue committed Oracle read"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'recent-work.zsh.*--dry-run' "Use Now checks recent work before falling back"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'Selected Signal' "Use Now explains selected recent-work signal"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'one executable move before the detailed read' "Use Now help one-move copy"
require_in_file "$ROOT/Makefile" 'one move, ask, capture, delegate, close' "Makefile Use Now one-move help"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'one move, compact context' "doctor Use Now one-move next step"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'Ask, Capture, Delegate, Close' "Use Now closed loop commands"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'work-block.zsh' "Use Now embeds Work Block"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'make outcome' "Use Now outcome command"
require_in_file "$ROOT/mac-app/scripts/use-now.zsh" 'did not launch, foreground, screenshot, quit, kill, or control Terminal Brain' "Use Now guardrail"
require_in_file "$ROOT/mac-app/scripts/first-minute.zsh" 'Terminal Brain First Minute' "non-launching first minute"
require_in_file "$ROOT/mac-app/scripts/first-minute.zsh" 'make use-now' "first minute starts with Use Now"
require_in_file "$ROOT/mac-app/scripts/first-minute.zsh" 'prove-value.zsh' "first minute includes proof"
require_in_file "$ROOT/mac-app/scripts/snapshot.zsh" 'local_start_here' "Start Here closed-app fallback"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make use-now' "non-launching next move Use Now"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'Start with one move' "non-launching next move one-move guidance"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make agent-prompt' "non-launching next move Agent Prompt"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make outcome' "non-launching next move Outcome"
require_in_file "$ROOT/mac-app/scripts/value.zsh" 'Terminal Brain Value Now' "non-launching value read"
require_in_file "$ROOT/mac-app/scripts/prove-value.zsh" 'Terminal Brain Value Proof' "non-launching value proof"
require_in_file "$ROOT/mac-app/scripts/prove-value.zsh" 'use-now.zsh' "value proof includes Use Now capture"
require_in_file "$ROOT/mac-app/scripts/prove-value.zsh" 'Value Proof Use Now Capture' "value proof captured signal"
require_in_file "$ROOT/mac-app/scripts/demo.zsh" 'Terminal Brain Demo' "non-launching demo"
require_in_file "$ROOT/mac-app/scripts/demo.zsh" 'Seeded Scenario' "demo seeded workspace"
require_in_file "$ROOT/mac-app/scripts/demo.zsh" 'Use It For Real' "demo real-use commands"
require_in_file "$ROOT/mac-app/scripts/playbook.zsh" 'Terminal Brain Playbook' "non-launching playbook"
require_in_file "$ROOT/mac-app/scripts/playbook.zsh" 'Pick The Situation' "playbook situation table"
require_in_file "$ROOT/mac-app/scripts/playbook.zsh" 'First Five Minutes' "playbook first loop"
require_in_file "$ROOT/mac-app/scripts/value-audit.zsh" 'Terminal Brain Value Audit' "non-launching value audit"
require_in_file "$ROOT/mac-app/scripts/value-audit.zsh" 'One-command Use Now path' "value audit covers Use Now"
require_in_file "$ROOT/mac-app/scripts/value-audit.zsh" 'Prompt-To-Artifact Checklist' "value audit checklist"
require_in_file "$ROOT/mac-app/scripts/value-audit.zsh" 'Remaining Gaps' "value audit gaps"
require_in_file "$ROOT/mac-app/scripts/design-audit.zsh" 'Terminal Brain Design Audit' "non-launching design audit"
require_in_file "$ROOT/mac-app/scripts/design-audit.zsh" 'Liquid Glass' "design audit liquid glass section"
require_in_file "$ROOT/mac-app/scripts/design-audit.zsh" 'transparent titlebar' "design audit titlebar evidence"
require_in_file "$ROOT/mac-app/scripts/design-audit.zsh" 'profile menu' "design audit profile menu evidence"
require_in_file "$ROOT/mac-app/scripts/design-audit.zsh" 'explicit permission to open the app' "design audit visual permission boundary"
require_in_file "$ROOT/Makefile" '^visual-review-plan:' "visual review plan target"
require_in_file "$ROOT/mac-app/scripts/visual-review-plan.zsh" 'Terminal Brain Visual Review Plan' "non-launching visual review plan"
require_in_file "$ROOT/mac-app/scripts/visual-review-plan.zsh" 'Use Now opens first' "visual review checks Use Now first"
require_in_file "$ROOT/mac-app/scripts/visual-review-plan.zsh" 'Check Blindspots' "visual review checks Radar counter-signal"
require_in_file "$ROOT/mac-app/scripts/visual-review-plan.zsh" 'Capture as Idea' "visual review checks Blindspots capture"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Start with one move' "native Use Now one-move hero"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'label: "One Move"' "native Use Now one-move card"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'title: "Why this move"' "native Use Now rationale card"
require_in_file "$ROOT/mac-app/scripts/design-audit.zsh" 'never launches, foregrounds, quits, kills, screenshots, or controls Terminal Brain' "design audit guardrail"
require_in_file "$ROOT/mac-app/scripts/oracle-brief.zsh" 'Terminal Brain Oracle Brief' "non-launching Oracle Brief"
require_in_file "$ROOT/mac-app/scripts/oracle-brief.zsh" 'work-block.zsh' "Oracle Brief closed-app pull-forward"
require_in_file "$ROOT/mac-app/scripts/oracle-brief.zsh" 'make ask-commit' "Oracle Brief closed-app ask commit"
require_in_file "$ROOT/mac-app/scripts/oracle.zsh" 'local-fallback' "Oracle Ask closed-app fallback"
require_in_file "$ROOT/mac-app/scripts/oracle.zsh" 'write_local_commit' "Oracle Ask commit local fallback"
require_in_file "$ROOT/mac-app/scripts/agent-prompt.zsh" 'Terminal Brain Agent Prompt' "non-launching Agent Prompt"
require_in_file "$ROOT/mac-app/scripts/agent-prompt.zsh" 'make work-block' "Agent Prompt includes Work Block"
require_in_file "$ROOT/mac-app/scripts/agent-prompt.zsh" 'make bubble-up' "Agent Prompt includes Bubble Up"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'MCP tool contract valid' "non-launching doctor MCP check"
require_in_file "$ROOT/mac-app/scripts/audit.zsh" 'Terminal Brain Capability Audit' "non-launching capability audit"
require_in_file "$ROOT/mac-app/scripts/audit.zsh" 'Audit failed:' "capability audit enforces missing evidence"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'installed app executable matches current build' "doctor installed app freshness check"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'latest GitHub CI succeeded' "doctor CI state check"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'readiness: package ready' "doctor readiness verdict"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'Prompt Safety' "doctor prompt safety check"
require_in_file "$ROOT/mac-app/scripts/check-entrypoints.zsh" 'terminal_brain_value_now_markdown' "entrypoint fallback verifier"
require_in_file "$ROOT/Makefile" '^start-here:' "Start Here Make target"
require_in_file "$ROOT/Makefile" '^use-now:' "Use Now Make target"
require_in_file "$ROOT/Makefile" '^first-minute:' "First Minute Make target"
require_in_file "$ROOT/Makefile" '^now:' "Now Make target"
require_in_file "$ROOT/Makefile" '^sources:' "Sources Make target"
require_in_file "$ROOT/Makefile" '^memory:' "Memory Make target"
require_in_file "$ROOT/Makefile" '^memory-promote:' "Memory Promote Make target"
require_in_file "$ROOT/Makefile" '^recent-work:' "Recent Work Make target"
require_in_file "$ROOT/Makefile" '^outcome:' "Outcome Make target"
require_in_file "$ROOT/Makefile" '^status:' "Status Make target"
require_in_file "$ROOT/Makefile" '^processes:' "Processes Make target"
require_in_file "$ROOT/Makefile" '^cleanup-plan:' "Cleanup Plan Make target"
require_in_file "$ROOT/Makefile" '^support-bundle:' "Support Bundle Make target"
require_in_file "$ROOT/Makefile" '^next:' "Next Make target"
require_in_file "$ROOT/Makefile" '^value:' "Value Make target"
require_in_file "$ROOT/Makefile" '^prove-value:' "Value Proof Make target"
require_in_file "$ROOT/Makefile" '^demo:' "Demo Make target"
require_in_file "$ROOT/Makefile" '^playbook:' "Playbook Make target"
require_in_file "$ROOT/Makefile" '^value-audit:' "Value Audit Make target"
require_in_file "$ROOT/Makefile" '^design-audit:' "Design Audit Make target"
require_in_file "$ROOT/Makefile" '^idea:' "Idea Capture Make target"
require_in_file "$ROOT/Makefile" '^review:' "Review Queue Make target"
require_in_file "$ROOT/Makefile" '^review-status:' "Review Status Make target"
require_in_file "$ROOT/Makefile" '^bubble-up:' "Bubble Up Make target"
require_in_file "$ROOT/Makefile" '^work-block:' "Work Block Make target"
require_in_file "$ROOT/Makefile" '^oracle-brief:' "Oracle Brief Make target"
require_in_file "$ROOT/Makefile" '^agent-prompt:' "Agent Prompt Make target"
require_in_file "$ROOT/Makefile" '^doctor:' "Doctor Make target"
require_in_file "$ROOT/Makefile" '^audit:' "Audit Make target"

require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_runtime_status' "Runtime Status MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_use_now_markdown' "Use Now MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'one executable move first' "Use Now MCP one-move description"
require_in_file "$ROOT/mcp-server/server.mjs" 'args.idea' "Use Now MCP idea argument"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_first_minute_markdown' "First Minute MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_now_markdown' "Now MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_now' "Now structured MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_sources_markdown' "Source Inventory MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'sourcesMarkdown' "Source Inventory MCP fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_memory_brief_markdown' "Memory Brief MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'memoryBriefMarkdown' "Memory Brief MCP fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_memory_promote' "Memory Promote MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'promoteMemory' "Memory Promote MCP fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_recent_work_promote' "Recent Work MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'promoteRecentWork' "Recent Work MCP fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_process_map_markdown' "Process Map MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_cleanup_plan_markdown' "Cleanup Plan MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_support_bundle_markdown' "Support Bundle MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'handoffMarkdown' "Handoff MCP closed-app fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'localSnapshotMarkdown' "Snapshot Markdown MCP closed-app fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'localSnapshot' "Snapshot MCP closed-app fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'app-api-unreachable' "Status MCP local fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_next_markdown' "Next Move MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_doctor_markdown' "Doctor MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_value_now_markdown' "Value Now MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_value_proof_markdown' "Value Proof MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_demo_markdown' "Demo MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_playbook_markdown' "Playbook MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_value_audit_markdown' "Value Audit MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_oracle_brief_markdown' "Oracle Brief MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'agentPromptMarkdown' "Agent Prompt MCP fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_audit_markdown' "Audit MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_start_here_markdown' "Start Here MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'startHereMarkdown' "Start Here MCP closed-app fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_oracle_digest_markdown' "Oracle Digest MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_commit_outcome' "Outcome MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'oracleAskMarkdown' "Oracle Ask MCP local fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'localOracleCommit' "Oracle Commit MCP local fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'localOutcomeCommit' "Outcome Commit MCP local fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'captureIdea' "Idea MCP closed fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_review_queue_markdown' "Review Queue MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'setReviewStatus' "Review Status MCP closed fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_bubble_up_markdown' "Bubble Up MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_work_block_markdown' "Work Block MCP tool"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_runtime_status' "Runtime Status MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_use_now_markdown' "Use Now MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_first_minute_markdown' "First Minute MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_now_markdown' "Now MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_now' "Now structured MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_sources_markdown' "Source Inventory MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_memory_brief_markdown' "Memory Brief MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_memory_promote' "Memory Promote MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_recent_work_promote' "Recent Work MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_process_map_markdown' "Process Map MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_cleanup_plan_markdown' "Cleanup Plan MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_support_bundle_markdown' "Support Bundle MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_next_markdown' "Next Move MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_doctor_markdown' "Doctor MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_value_now_markdown' "Value Now MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_value_proof_markdown' "Value Proof MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_demo_markdown' "Demo MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_playbook_markdown' "Playbook MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_value_audit_markdown' "Value Audit MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_review_queue_markdown' "Review Queue MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_bubble_up_markdown' "Bubble Up MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_work_block_markdown' "Work Block MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_oracle_brief_markdown' "Oracle Brief MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_audit_markdown' "Audit MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_start_here_markdown' "Start Here MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_oracle_digest_markdown' "Oracle Digest MCP contract"

require_in_file "$ROOT/AGENTS.md" 'Do not use Computer Use' "UI automation guardrail"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_first_minute_markdown' "agent first minute instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_value_now_markdown' "agent value instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_value_proof_markdown' "agent value proof instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_review_queue_markdown' "agent review queue instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_oracle_brief_markdown' "agent Oracle Brief instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_agent_prompt_markdown' "agent prompt instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_next_markdown' "agent next move instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_doctor_markdown' "agent doctor instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_audit_markdown' "agent audit instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_runtime_status' "agent runtime status instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_now_markdown' "agent Now instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_process_map_markdown' "agent process map instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_cleanup_plan_markdown' "agent cleanup plan instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_support_bundle_markdown' "agent support bundle instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_start_here_markdown' "agent Start Here instruction"
require_in_file "$ROOT/README.md" 'START-HERE.md' "README Start Here link"
require_in_file "$ROOT/README.md" 'make use-now' "README Use Now command"
require_in_file "$ROOT/README.md" 'make first-minute' "README First Minute command"
require_in_file "$ROOT/README.md" 'make demo' "README Demo command"
require_in_file "$ROOT/README.md" 'make playbook' "README Playbook command"
require_in_file "$ROOT/README.md" 'make value-audit' "README Value Audit command"
require_in_file "$ROOT/README.md" 'make design-audit' "README Design Audit command"
require_in_file "$ROOT/README.md" 'make idea' "README Idea command"
require_in_file "$ROOT/README.md" 'make processes' "README process map command"
require_in_file "$ROOT/README.md" 'terminal_brain_value_proof_markdown' "README Value Proof MCP tool"
require_in_file "$ROOT/README.md" 'make oracle-brief' "README Oracle Brief command"
require_in_file "$ROOT/README.md" 'make bubble-up' "README Bubble Up command"
require_in_file "$ROOT/README.md" 'make work-block' "README Work Block command"
require_in_file "$ROOT/README.md" 'make agent-prompt' "README Agent Prompt command"
require_in_file "$ROOT/README.md" 'make cleanup-plan' "README cleanup plan command"
require_in_file "$ROOT/README.md" 'make support-bundle' "README support bundle command"
require_in_file "$ROOT/START-HERE.md" 'make value' "repo value command"
require_in_file "$ROOT/START-HERE.md" 'make use-now' "repo Use Now command"
require_in_file "$ROOT/START-HERE.md" 'make demo' "repo demo command"
require_in_file "$ROOT/START-HERE.md" 'make playbook' "repo playbook command"
require_in_file "$ROOT/START-HERE.md" 'make value-audit' "repo value audit command"
require_in_file "$ROOT/START-HERE.md" 'make design-audit' "repo design audit command"
require_in_file "$ROOT/START-HERE.md" 'make oracle-brief' "repo Oracle Brief command"
require_in_file "$ROOT/START-HERE.md" 'make bubble-up' "repo Bubble Up command"
require_in_file "$ROOT/START-HERE.md" 'make work-block' "repo Work Block command"
require_in_file "$ROOT/START-HERE.md" 'make agent-prompt' "repo Agent Prompt command"
require_in_file "$ROOT/START-HERE.md" 'make now' "repo Now command"
require_in_file "$ROOT/START-HERE.md" 'make next' "repo next command"
require_in_file "$ROOT/START-HERE.md" 'make status' "repo status command"
require_in_file "$ROOT/START-HERE.md" 'make processes' "repo process map command"
require_in_file "$ROOT/START-HERE.md" 'make cleanup-plan' "repo cleanup plan command"
require_in_file "$ROOT/START-HERE.md" 'make support-bundle' "repo support bundle command"
require_in_file "$ROOT/START-HERE.md" 'make outcome' "repo outcome close loop"

if [[ "$missing" != "0" ]]; then
  exit 1
fi

echo "value surfaces ok"
