#!/usr/bin/env zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

missing=0

require_in_file() {
  local file="$1"
  local pattern="$2"
  local label="$3"

  if ! grep -qE -- "$pattern" "$file"; then
    echo "Missing value surface: $label in $file" >&2
    missing=1
  fi
}

require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Start Here' "Start Here app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Terminal Brain Now' "Now app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Value Now' "Value Now app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'selectedSection = "work-block"' "Work Block default app section"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'workBlockView' "Work Block app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Top Review Action' "Work Block direct review actions"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'delegateOracleCommitToStartWork\(topReview\)' "Work Block delegate action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'firstMinuteView' "First Minute app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'focusIdeaCapturePanel\(focus\)' "First Minute capture thought panel"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open First Minute' "command palette can open First Minute"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Work Block' "command palette can open Work Block"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Open Now' "command palette can open Now"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Start Here' "Start Here menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Now' "Now menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Oracle Brief' "Oracle Brief menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Process Map' "Process Map menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Cleanup Plan' "Cleanup Plan menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Support Bundle' "Support Bundle menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/TerminalBrainApp.swift" 'Copy Work Block' "Work Block menu bar/menu command"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Commit Outcome' "in-app outcome close loop"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/ContentView.swift" 'Oracle Digest' "Oracle Digest app surface"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func commitOutcome' "in-app structured outcome writer"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyFirstMinute' "in-app First Minute copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyNow' "in-app Now copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyOracleBrief' "in-app Oracle Brief copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyProcessMap' "in-app Process Map copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyCleanupPlan' "in-app Cleanup Plan copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copySupportBundle' "in-app Support Bundle copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/BrainStatusModel.swift" 'func copyWorkBlock' "in-app Work Block copy action"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyNowIntent' "Copy Now App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyFirstMinuteIntent' "Copy First Minute App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyOracleBriefIntent' "Copy Oracle Brief App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyProcessMapIntent' "Copy Process Map App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyCleanupPlanIntent' "Copy Cleanup Plan App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopySupportBundleIntent' "Copy Support Bundle App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyWorkBlockIntent' "Copy Work Block App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyValueProofIntent' "Copy Value Proof App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CommitBrainOutcomeIntent' "Commit Outcome App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyStartHereIntent' "Copy Start Here App Shortcut"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/AppShortcuts.swift" 'CopyOracleDigestIntent' "Copy Oracle Digest App Shortcut"

require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/start-here/markdown"' "Start Here API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/first-minute/markdown"' "First Minute API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/now/markdown"' "Now API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/now"' "Now JSON API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/cleanup-plan/markdown"' "Cleanup Plan API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/process-map/markdown"' "Process Map API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/support-bundle/markdown"' "Support Bundle API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/work-block/markdown"' "Work Block API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/value-proof/markdown"' "Value Proof API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/oracle/brief/markdown"' "Oracle Brief API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/oracle-digest/markdown"' "Oracle Digest API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" '"/outcomes/commit"' "Outcome commit API route"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'reviewStatus: "accepted"' "outcomes close as accepted"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum StartHereSnapshot' "Start Here Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum FirstMinuteSnapshot' "First Minute Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum NowSnapshot' "Now Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum CleanupPlanSnapshot' "Cleanup Plan Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum ProcessMapSnapshot' "Process Map Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum SupportBundleSnapshot' "Support Bundle Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum WorkBlockSnapshot' "Work Block Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum ValueProofSnapshot' "Value Proof Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'static func markdown\(\) async -> String' "Oracle Brief Markdown artifact"
require_in_file "$ROOT/mac-app/Sources/TerminalBrain/LocalControlServer.swift" 'enum OracleDigestSnapshot' "Oracle Digest artifact"

require_in_file "$ROOT/mac-app/scripts/snapshot.zsh" '--start-here' "Start Here CLI flag"
require_in_file "$ROOT/mac-app/scripts/snapshot.zsh" '--digest' "Oracle Digest CLI flag"
require_in_file "$ROOT/mac-app/scripts/idea.zsh" 'local-fallback' "Idea CLI local fallback"
require_in_file "$ROOT/mac-app/scripts/idea.zsh" 'reviewStatus: new' "Idea fallback opens review"
require_in_file "$ROOT/mac-app/scripts/review.zsh" 'Terminal Brain Review Queue' "Review Queue CLI"
require_in_file "$ROOT/mac-app/scripts/review.zsh" 'make review-status' "Review Queue action commands"
require_in_file "$ROOT/mac-app/scripts/review.zsh" 'did not launch, foreground, quit, kill, or control Terminal Brain' "Review Queue guardrail"
require_in_file "$ROOT/mac-app/scripts/review-status.zsh" 'reviewStatus' "Review Status CLI"
require_in_file "$ROOT/mac-app/scripts/review-status.zsh" 'did not launch or foreground Terminal Brain' "Review Status guardrail"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'Terminal Brain Bubble Up' "Bubble Up CLI"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'What You May Not Be Considering' "Bubble Up under-considered signals"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'make review-status' "Bubble Up action commands"
require_in_file "$ROOT/mac-app/scripts/bubble-up.zsh" 'did not launch, foreground, quit, kill, or control Terminal Brain' "Bubble Up guardrail"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'Terminal Brain Work Block' "Work Block CLI"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'bubble-up.zsh' "Work Block includes Bubble Up"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'review.zsh' "Work Block includes Review Queue"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'make outcome' "Work Block close-loop command"
require_in_file "$ROOT/mac-app/scripts/work-block.zsh" 'did not launch, foreground, quit, kill, or control Terminal Brain' "Work Block guardrail"
require_in_file "$ROOT/mac-app/scripts/outcome.zsh" '/outcomes/commit' "Outcome CLI API writeback"
require_in_file "$ROOT/mac-app/scripts/outcome.zsh" 'local-fallback' "Outcome CLI local fallback"
require_in_file "$ROOT/mac-app/scripts/outcome.zsh" 'reviewStatus: accepted' "Outcome fallback closes as accepted"
require_in_file "$ROOT/mac-app/scripts/now.zsh" 'Terminal Brain Now' "non-launching Now orientation"
require_in_file "$ROOT/mac-app/scripts/now.zsh" 'make outcome' "Now outcome close loop"
require_in_file "$ROOT/mac-app/scripts/status.zsh" 'App process' "non-launching status process check"
require_in_file "$ROOT/mac-app/scripts/processes.zsh" 'Terminal Brain Process Map' "non-launching process map"
require_in_file "$ROOT/mac-app/scripts/processes.zsh" 'did not launch, foreground, quit, kill, or control anything' "process map guardrail"
require_in_file "$ROOT/mac-app/scripts/cleanup-plan.zsh" 'Terminal Brain Cleanup Plan' "non-destructive cleanup plan"
require_in_file "$ROOT/mac-app/scripts/cleanup-plan.zsh" 'did not launch, foreground, quit, kill, or control anything' "cleanup plan guardrail"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Terminal Brain Support Bundle' "non-launching support bundle"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Oracle Brief' "support bundle includes Oracle Brief"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Bubble Up' "support bundle includes Bubble Up"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'Work Block' "support bundle includes Work Block"
require_in_file "$ROOT/mac-app/scripts/support-bundle.zsh" 'did not launch, foreground, quit, kill, or control anything' "support bundle guardrail"
require_in_file "$ROOT/mac-app/scripts/first-minute.zsh" 'Terminal Brain First Minute' "non-launching first minute"
require_in_file "$ROOT/mac-app/scripts/first-minute.zsh" 'prove-value.zsh' "first minute includes proof"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make oracle-brief' "non-launching next move Oracle Brief"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make work-block' "non-launching next move Work Block"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make bubble-up' "non-launching next move Bubble Up"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make agent-prompt' "non-launching next move Agent Prompt"
require_in_file "$ROOT/mac-app/scripts/next.zsh" 'make outcome' "non-launching next move Outcome"
require_in_file "$ROOT/mac-app/scripts/value.zsh" 'Terminal Brain Value Now' "non-launching value read"
require_in_file "$ROOT/mac-app/scripts/prove-value.zsh" 'Terminal Brain Value Proof' "non-launching value proof"
require_in_file "$ROOT/mac-app/scripts/oracle-brief.zsh" 'Terminal Brain Oracle Brief' "non-launching Oracle Brief"
require_in_file "$ROOT/mac-app/scripts/agent-prompt.zsh" 'Terminal Brain Agent Prompt' "non-launching Agent Prompt"
require_in_file "$ROOT/mac-app/scripts/agent-prompt.zsh" 'make work-block' "Agent Prompt includes Work Block"
require_in_file "$ROOT/mac-app/scripts/agent-prompt.zsh" 'make bubble-up' "Agent Prompt includes Bubble Up"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'MCP tool contract valid' "non-launching doctor MCP check"
require_in_file "$ROOT/mac-app/scripts/audit.zsh" 'Terminal Brain Capability Audit' "non-launching capability audit"
require_in_file "$ROOT/mac-app/scripts/audit.zsh" 'Audit failed:' "capability audit enforces missing evidence"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'installed app executable matches current build' "doctor installed app freshness check"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'latest GitHub CI succeeded' "doctor CI state check"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'readiness: package ready' "doctor readiness verdict"
require_in_file "$ROOT/mac-app/scripts/doctor.zsh" 'Prompt Safety' "doctor prompt safety check"
require_in_file "$ROOT/mac-app/scripts/check-entrypoints.zsh" 'terminal_brain_value_now_markdown' "entrypoint fallback verifier"
require_in_file "$ROOT/Makefile" '^start-here:' "Start Here Make target"
require_in_file "$ROOT/Makefile" '^first-minute:' "First Minute Make target"
require_in_file "$ROOT/Makefile" '^now:' "Now Make target"
require_in_file "$ROOT/Makefile" '^outcome:' "Outcome Make target"
require_in_file "$ROOT/Makefile" '^status:' "Status Make target"
require_in_file "$ROOT/Makefile" '^processes:' "Processes Make target"
require_in_file "$ROOT/Makefile" '^cleanup-plan:' "Cleanup Plan Make target"
require_in_file "$ROOT/Makefile" '^support-bundle:' "Support Bundle Make target"
require_in_file "$ROOT/Makefile" '^next:' "Next Make target"
require_in_file "$ROOT/Makefile" '^value:' "Value Make target"
require_in_file "$ROOT/Makefile" '^prove-value:' "Value Proof Make target"
require_in_file "$ROOT/Makefile" '^idea:' "Idea Capture Make target"
require_in_file "$ROOT/Makefile" '^review:' "Review Queue Make target"
require_in_file "$ROOT/Makefile" '^review-status:' "Review Status Make target"
require_in_file "$ROOT/Makefile" '^bubble-up:' "Bubble Up Make target"
require_in_file "$ROOT/Makefile" '^work-block:' "Work Block Make target"
require_in_file "$ROOT/Makefile" '^oracle-brief:' "Oracle Brief Make target"
require_in_file "$ROOT/Makefile" '^agent-prompt:' "Agent Prompt Make target"
require_in_file "$ROOT/Makefile" '^doctor:' "Doctor Make target"
require_in_file "$ROOT/Makefile" '^audit:' "Audit Make target"

require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_runtime_status' "Runtime Status MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_first_minute_markdown' "First Minute MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_now_markdown' "Now MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_now' "Now structured MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_process_map_markdown' "Process Map MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_cleanup_plan_markdown' "Cleanup Plan MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_support_bundle_markdown' "Support Bundle MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_next_markdown' "Next Move MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_doctor_markdown' "Doctor MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_value_now_markdown' "Value Now MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_value_proof_markdown' "Value Proof MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_oracle_brief_markdown' "Oracle Brief MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'agentPromptMarkdown' "Agent Prompt MCP fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_audit_markdown' "Audit MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_start_here_markdown' "Start Here MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_oracle_digest_markdown' "Oracle Digest MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_commit_outcome' "Outcome MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'captureIdea' "Idea MCP closed fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_review_queue_markdown' "Review Queue MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'setReviewStatus' "Review Status MCP closed fallback"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_bubble_up_markdown' "Bubble Up MCP tool"
require_in_file "$ROOT/mcp-server/server.mjs" 'terminal_brain_work_block_markdown' "Work Block MCP tool"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_runtime_status' "Runtime Status MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_first_minute_markdown' "First Minute MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_now_markdown' "Now MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_now' "Now structured MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_process_map_markdown' "Process Map MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_cleanup_plan_markdown' "Cleanup Plan MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_support_bundle_markdown' "Support Bundle MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_next_markdown' "Next Move MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_doctor_markdown' "Doctor MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_value_now_markdown' "Value Now MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_value_proof_markdown' "Value Proof MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_review_queue_markdown' "Review Queue MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_bubble_up_markdown' "Bubble Up MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_work_block_markdown' "Work Block MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_oracle_brief_markdown' "Oracle Brief MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_audit_markdown' "Audit MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_start_here_markdown' "Start Here MCP contract"
require_in_file "$ROOT/mcp-server/expected-tools.json" 'terminal_brain_oracle_digest_markdown' "Oracle Digest MCP contract"

require_in_file "$ROOT/AGENTS.md" 'Do not use Computer Use' "UI automation guardrail"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_first_minute_markdown' "agent first minute instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_value_now_markdown' "agent value instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_value_proof_markdown' "agent value proof instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_review_queue_markdown' "agent review queue instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_oracle_brief_markdown' "agent Oracle Brief instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_agent_prompt_markdown' "agent prompt instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_next_markdown' "agent next move instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_doctor_markdown' "agent doctor instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_audit_markdown' "agent audit instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_runtime_status' "agent runtime status instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_now_markdown' "agent Now instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_process_map_markdown' "agent process map instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_cleanup_plan_markdown' "agent cleanup plan instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_support_bundle_markdown' "agent support bundle instruction"
require_in_file "$ROOT/AGENTS.md" 'terminal_brain_start_here_markdown' "agent Start Here instruction"
require_in_file "$ROOT/README.md" 'START-HERE.md' "README Start Here link"
require_in_file "$ROOT/README.md" 'make first-minute' "README First Minute command"
require_in_file "$ROOT/README.md" 'make idea' "README Idea command"
require_in_file "$ROOT/README.md" 'make processes' "README process map command"
require_in_file "$ROOT/README.md" 'terminal_brain_value_proof_markdown' "README Value Proof MCP tool"
require_in_file "$ROOT/README.md" 'make oracle-brief' "README Oracle Brief command"
require_in_file "$ROOT/README.md" 'make bubble-up' "README Bubble Up command"
require_in_file "$ROOT/README.md" 'make work-block' "README Work Block command"
require_in_file "$ROOT/README.md" 'make agent-prompt' "README Agent Prompt command"
require_in_file "$ROOT/README.md" 'make cleanup-plan' "README cleanup plan command"
require_in_file "$ROOT/README.md" 'make support-bundle' "README support bundle command"
require_in_file "$ROOT/START-HERE.md" 'make value' "repo value command"
require_in_file "$ROOT/START-HERE.md" 'make oracle-brief' "repo Oracle Brief command"
require_in_file "$ROOT/START-HERE.md" 'make bubble-up' "repo Bubble Up command"
require_in_file "$ROOT/START-HERE.md" 'make work-block' "repo Work Block command"
require_in_file "$ROOT/START-HERE.md" 'make agent-prompt' "repo Agent Prompt command"
require_in_file "$ROOT/START-HERE.md" 'make now' "repo Now command"
require_in_file "$ROOT/START-HERE.md" 'make next' "repo next command"
require_in_file "$ROOT/START-HERE.md" 'make status' "repo status command"
require_in_file "$ROOT/START-HERE.md" 'make processes' "repo process map command"
require_in_file "$ROOT/START-HERE.md" 'make cleanup-plan' "repo cleanup plan command"
require_in_file "$ROOT/START-HERE.md" 'make support-bundle' "repo support bundle command"
require_in_file "$ROOT/START-HERE.md" 'make outcome' "repo outcome close loop"

if [[ "$missing" != "0" ]]; then
  exit 1
fi

echo "value surfaces ok"
